### ISSUE TITLE
Can get post card to show any info

### ISSUE THREAD

**Issue by hwikene** [ezand/lovelace-posten-card#1]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Home Assistant Supervised (0.114.2)
**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
This is what i get when i have added the code:
![2020-08-20_10h08_09](https://user-images.githubusercontent.com/17985923/90741386-7824b280-e2cf-11ea-9fa7-657e120508b5.jpg)
And this is my settings:
![2020-08-20_10h07_59](https://user-images.githubusercontent.com/17985923/90741518-807ced80-e2cf-11ea-98f4-72887d6cafac.jpg)
Sensor:
![image](https://user-images.githubusercontent.com/17985923/90741114-6511e280-e2cf-11ea-8915-ae6329129089.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
I get no error in my log.

**Comment by ezand** [comment]
Thanks @hwikene I noticed the same. I believe the issue was actually with the sensor that was references in the readme. The sensor is updated now. Could you please try updating your sensor and see if that helps?

https://github.com/ezand/home-assistant-config/blob/master/sensors/posten-delivery-days.yaml

**Comment by hwikene** [comment]
That did the trick :) 
Thanks! 
![image](https://user-images.githubusercontent.com/17985923/90749657-06029c80-e2d4-11ea-9354-a717a275a0d9.png)
